server:
  port: 8010


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myapp?setTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


#配置日志
logging:
#此处存放日志的路径
  path:
    config: classpath:config/logback-spring.xml
  #指定不同目录下的日志的级别
  level:
    com.example.myapptest.mapper: DEBUG
